# This Workflow is to auto sync current repository commits to a secondary repository

name: Auto Sync To Second Repo
run-name: Syncing @${{ github.actor }}'s changes to second repository
on:
  push:
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
    

jobs:
  SyncCommitToSecondRepo:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get latest commit'
        uses: actions/checkout@v3
        with:
          path: 'src'
        
      - name: 'Get Second Repo'
        uses: actions/checkout@v3
        with:
          path: 'main'
          
        
