# This Workflow is to auto sync current repository commits to a secondary repository

name: Auto Sync Changes To Second Repo
run-name: Syncing @${{ github.actor }}'s changes to second repository
on:
  push:
    branches: master
      
  pull_request:
    branches: master

jobs:
  SyncCommitToSecondRepo:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check main repo'
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      
      - name: 'Configuration'
        run: |
          git config --global user.name 'John'
          git config --global user.email 'John@no.reply.github.com'
          git status --verbose

      - name: 'Adding Second repo'
        run: |
          git remote set-url origin --push --add https://github.com/John-2525/Secondary_Repo.git
          git remote --verbose

      #- name: 'Syncing with second repo'
       # run: |
        #  git checkout remotes/origin/master
         # git add .
          #git commit -m "Test"
          #git push -u --verbose secondOrigin master
