# This Workflow is to auto sync current repository commits to a secondary repository

name: Auto Sync Changes To Second Repo
run-name: Syncing @${{ github.actor }}'s changes to second repository
on:
  push:
    branches:
      [master]
      
  pull_request:

jobs:
  SyncCommitToSecondRepo:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check main repo'
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      
      - name: 'Add second repo'
        run: |
          git config --global user.name 'John'
          git config --global user.email 'John@no.reply.github.com'
          git status
          git remote add secondOrigin https://github.com/John-2525/Secondary_Repo
          git status secondOrigin

      - name: 'Pushing changes to second repo'
        run: |
          git fetch
          git push -u secondOrigin
          git remote remove secondOrigin
          
