# This Workflow is to auto sync current repository commits to a secondary repository

name: Auto Sync To Second Repo
run-name: Syncing @${{ github.actor }}'s changes to second repository
on:
  push:
    paths-ignore:
      - '.github/workflows/**'
    

jobs:
  SyncCommitToSecondRepo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.name 'John'
          git config --global user.email 'John@users.noreply.github.com'
          git remote add SecondaryRepo https://github.com/John-2525/Test-Recipient.git
          git commit -m "Generated"
          git push -m SecondaryRepo
          git remote remove SecondaryRepo
          
        
