# This Workflow is to auto sync current repository commits to a secondary repository

name: Auto Sync To Second Repo
run-name: Syncing @${{ github.actor }}'s changes to second repository
on:
  push:
    branches:
      [main]
    paths-ignore:
      - '.github/workflows/**'
      
  pull_request:
    branches:
      [main]
    paths-ignore:
      - '.github/workflows/**'
    

jobs:
  SyncCommitToSecondRepo:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check main repo'
        uses: actions/checkout@v3
        with:
          path: 'src'
      
      - name: 'Add second repo'
        run: git remote add secondOrigin https://github.com/John-2525/Test-Recipient.git
    
      #- name: '
